# Generated by Django 4.0.7 on 2022-09-22 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('pic', models.ImageField(blank=True, default='Adherdoc.png', null=True, upload_to='')),
                ('ph_no', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Mobile phone')),
                ('alternative_ph_no', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Mobile phone')),
                ('Email', models.CharField(max_length=50, null=True)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('nearestpolicestation', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_no', models.CharField(max_length=50, null=True)),
                ('device_type', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('device_location', models.CharField(max_length=200, null=True)),
                ('m2m_reg_no', models.CharField(max_length=50, null=True)),
                ('Active_status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MainFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('ph_no', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('gasVal', models.CharField(max_length=50, null=True)),
                ('paymentStatus', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
