# Generated by Django 4.0.7 on 2022-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_info',
            name='device_type',
            field=models.CharField(choices=[('load cell added', 'With load Cell'), ('load cell not added', 'Without load Cell')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mainfeed',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
