# Generated by Django 4.0.7 on 2022-09-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0002_alter_device_info_device_type_alter_mainfeed_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmergencyContectperson_name', models.CharField(max_length=50, null=True)),
                ('EmergencyContectperson_ph_no', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='device_info',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IoclDevApp.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(to='IoclDevApp.tag'),
        ),
    ]
