# Generated by Django 4.0.7 on 2022-09-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0003_tag_device_info_customer_customer_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='EmergencyContectperson_ph_no',
        ),
    ]
