# Generated by Django 4.0.7 on 2022-09-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0005_remove_customer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(to='IoclDevApp.tag'),
        ),
        migrations.AlterField(
            model_name='mainfeed',
            name='Customername',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='EmergencyContectperson_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
