# Generated by Django 4.0.7 on 2022-09-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0006_customer_tags_alter_mainfeed_customername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainfeed',
            name='Customername',
        ),
    ]
