# Generated by Django 4.0.7 on 2022-09-30 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0007_remove_mainfeed_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfeed',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IoclDevApp.customer'),
        ),
        migrations.AddField(
            model_name='mainfeed',
            name='Device_Info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IoclDevApp.device_info'),
        ),
    ]
