# Generated by Django 4.0.7 on 2022-09-30 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0008_mainfeed_customer_mainfeed_device_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=0)),
                ('remarks', models.CharField(max_length=50, null=True)),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IoclDevApp.customer')),
                ('Device_Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IoclDevApp.device_info')),
            ],
        ),
    ]
