# Generated by Django 4.0.7 on 2022-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0009_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device_info',
            name='device_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
