# Generated by Django 4.0.7 on 2023-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0010_device_info_status_alter_device_info_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=50, null=True)),
                ('QR_Data', models.CharField(max_length=150, null=True)),
                ('Qr_no', models.CharField(max_length=50, null=True)),
                ('Purches_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('UCode', models.CharField(max_length=50, null=True)),
                ('OTP', models.CharField(max_length=50, null=True)),
                ('Ph_No', models.CharField(max_length=50, null=True)),
                ('Sale_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tags',
        ),
        migrations.AlterField(
            model_name='device_info',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Sold', 'Sold')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
