# Generated by Django 4.0.7 on 2023-09-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0011_transiction_remove_customer_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transiction',
            name='UCode',
        ),
    ]
