# Generated by Django 4.0.7 on 2023-09-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0012_remove_transiction_ucode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transiction',
            name='uid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
