# Generated by Django 4.0.7 on 2023-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0013_transiction_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transiction',
            name='OTP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transiction',
            name='Ph_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transiction',
            name='Sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transiction',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
