# Generated by Django 4.0.7 on 2023-09-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0014_alter_transiction_otp_alter_transiction_ph_no_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transiction',
            table='TRANSACTION',
        ),
    ]
