# Generated by Django 4.0.7 on 2023-09-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoclDevApp', '0015_alter_transiction_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transiction',
            table='Transiction',
        ),
    ]
